### ISSUE TITLE
english ui?

### ISSUE THREAD

**Issue by shahram7** [jiangnianshun/django-mdict#6]
Hi thank you for your great work.
I'm very happy to find your project. I deployed your docker via portainer with following stack:
```
version: '3'

services:
  django-mdict:
    image: wbsu2003/django-mdict:v1
    container_name: django-mdict
    command: python3 manage.py runserver 0.0.0.0:8090 --noreload
    ports:
      - 18000:8090
    volumes:
      - /mnt/nvme/other/glossaries/mdict/flaskmdict:/code/media/mdict/doc
```

is it possible to change the UI language to english and set darkmode to default?

I hope you had a good golden week : )

Best regards,
Shahram
